### ISSUE TITLE
Flameshot miss XDG_CURRENT_DESKTOP ?

### ISSUE THREAD

**Issue by GreyXor** [alebastr/sway-systemd#19]
Hello,
i'm using archlinux and I have installed the sway-systemd aur package.
I have these lines at the bottom of my sway configuration.

```bash
exec /usr/lib/sway-systemd/session.sh --with-cleanup
exec /usr/lib/sway-systemd/assign-cgroups.py
```

Now I try to run flameshot but I get this error
```bash
flameshot: error: Unable to detect desktop environment (GNOME? KDE? Sway? ...)
flameshot: error: Hint: try setting the XDG_CURRENT_DESKTOP environment variable.
```

and this is my `systemctl --user show-environment`

```bash
HOME=/home/gregoire
LANG=en_US.UTF-8
LOGNAME=gregoire
MAIL=/var/spool/mail/gregoire
PATH=/usr/local/bin:/usr/bin
SHELL=/usr/bin/zsh
SYSTEMD_EXEC_PID=878
SYSTEMD_HOME=1
SYSTEMD_HOME_SUSPEND=0
USER=gregoire
XDG_RUNTIME_DIR=/run/user/60177
DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/60177/bus
DISPLAY=:0
I3SOCK=/run/user/60177/sway-ipc.60177.887.sock
SWAYSOCK=/run/user/60177/sway-ipc.60177.887.sock
WAYLAND_DISPLAY=wayland-1
XDG_CURRENT_DESKTOP=sway
XDG_SESSION_DESKTOP=sway
XDG_SESSION_TYPE=wayland
```

![image](https://github.com/alebastr/sway-systemd/assets/79602273/be059d4a-1572-449b-8ea1-26899e369a14)

Also with
`XDG_CURRENT_DESKTOP=sway flameshot` it's working

**Comment by alebastr** [comment]
Setting the environment for an arbitrary user app launched from Sway is not related to systemd integration and is out of scope for this project (it's mentioned in the readme with a link to discussion in #6).

Note that it is not even possible to modify the environment from within Sway, and anything that happens before (display manager, `sway.desktop`, `/usr/bin/sway`) is owned by corresponding packages.

See also: swaywm/sway#4876.
