### ISSUE TITLE
Unable to set keyboard parameters when locale1-xkb-config is used

### ISSUE THREAD

**Issue by Sunderland93** [alebastr/sway-systemd#21]
Hello and thanks for that awesome project! I have a problem with` locale1-xkb-config`. When it enabled (and launched with https://github.com/alebastr/sway-systemd/blob/main/config.d/95-system-keyboard-config.conf.in), I'm unable to change my keyboard layout, variant, and other parameters in Sway config. `localectl` output:

```
System Locale: LANG=ru_RU.UTF-8
       VC Keymap: us
      X11 Layout: us
       X11 Model: pc105
```

And this is in my Sway config:

```
# Keyboard layout
  input type:keyboard {
   xkb_layout us,ru
   xkb_options grp:caps_toggle
}
```

**Comment by alebastr** [comment]
`locale1-xkb-config` makes Sway follow the global keyboard options set with localectl, and by virtue of being a script it works *after* the sway configuration is parsed/applied. I.e. it will always overwrite your configuration for `input type:keyboard`.

Either you want system-wide keyboard layout and thus have to use `localectl set-x11-keymap "us,ru" "" "" "grp:caps_toggle"`, or you don't really need the `locale1-xkb-config` :)
