### ISSUE TITLE
Missing config files in meson.build?

### ISSUE THREAD

**Issue by itaranto** [alebastr/sway-systemd#22]
Currently, neither of these config files:

- `95-system-keyboard-config.conf.in`
- `95-xdg-desktop-autostart.conf.in`

Are being added to the `configs` list in `meson.build` when building with the following flags respectively:

- `-Dlocale1=true`
- `-Dautostart=true`

Does this make any sense?

**Comment by alebastr** [comment]
See https://github.com/alebastr/sway-systemd/pull/20#issuecomment-1556260429.
