### ISSUE TITLE
Waybar failed to start after login from greetd

### ISSUE THREAD

**Issue by Sunderland93** [alebastr/sway-systemd#24]
Greetings. I installed `sway-systemd` on Debian along with Sway and Waybar. Waybar starts normally via `waybar.service` , however if I exit the Sway session (I'm using `greetd + tuigreet`) Waybar tries to start before Sway and thus fails. I tried changing `graphical-session.target` to `sway-session.target` in `waybar.service` , but to no avail. The only way out is to activate `waybar.service` , but then Waybar starts running all the time, for example, it cannot be terminated (it will restart). Please tell me if there is a solution to this problem?

**Comment by alebastr** [comment]
The `session.sh` script in this repository is executed once Sway is ready
to accept connection and will stop the session target before the compositor
exits. `PartOf=graphical-session.target` in `waybar.service` should
propagate the stop command to waybar. It works for me with clean
configuration and kanshi and I don't expect waybar to be doing anything
special.

Can you please check that
 - nothing else in your configuration tries to start
`graphical-session.target` or `sway-session.target`
 - `graphical-session.target` is stopped after you log out

If you are redirecting the Sway output to the journal with systemd-cat, the
timestamps of the service status events and the Sway log messages could
also help you troubleshoot the problem.

**Comment by Sunderland93** [comment]
Waybar's log after relogin:

```
июн 09 04:57:27 tileos-dev waybar[3178]: cannot open display: 
июн 09 04:57:27 tileos-dev waybar[3204]: cannot open display: 
июн 09 04:57:28 tileos-dev waybar[3248]: cannot open display: 
июн 09 04:57:28 tileos-dev waybar[3251]: cannot open display: 
```

**Comment by Sunderland93** [comment]
Also, Sway is started from this script (adapted from Fedora):

```
#!/usr/bin/env sh

## General exports
export XDG_CURRENT_DESKTOP=sway
export XDG_SESSION_DESKTOP=sway
export XDG_SESSION_TYPE=wayland

# Check if system is running in virtual machine
case "$(systemd-detect-virt)" in
qemu)
  export WLR_RENDERER=pixman
  export WLR_NO_HARDWARE_CURSORS=1
  ;;
kvm)
  export WLR_NO_HARDWARE_CURSORS=1
  ;;
oracle)
  export WLR_NO_HARDWARE_CURSORS=1
  ;;
esac

# Apply Nvidia-specific variables
if [ -d /sys/module/nvidia ]; then
    export WLR_NO_HARDWARE_CURSORS=1
    export GBM_BACKEND=nvidia-drm
    export __GLX_VENDOR_LIBRARY_NAME=nvidia
    export LIBVA_DRIVER_NAME=nvidia
fi

## Load system environment customizations
if [ -f /etc/sway/environment ]; then
    set -o allexport
    # shellcheck source=/dev/null
    . /etc/sway/environment
    set +o allexport
fi

## Load user environment customizations
if [ -f "${XDG_CONFIG_HOME:-$HOME/.config}/sway/environment" ]; then
    set -o allexport
    # shellcheck source=/dev/null
    . "${XDG_CONFIG_HOME:-$HOME/.config}/sway/environment"
    set +o allexport
fi

# Check if Nvidia driver installed, start Sway and send output to the journal
if [ -d /sys/module/nvidia ]; then
    exec systemd-cat -- /usr/bin/sway --unsupported-gpu $@
else
    exec systemd-cat -- /usr/bin/sway $@
fi
```

**Comment by Sunderland93** [comment]
Same problem https://github.com/Alexays/Waybar/issues/1371

**Comment by alebastr** [comment]
Ugh. I really have no idea how that's happening. The [cleanup code in `session.sh`](https://github.com/alebastr/sway-systemd/blob/68c8ce77d9ecdd8037b42ef7b4728b09d924b863/src/session.sh#L122-L130) should stop the target even if Sway is abnormally terminated. That is, if you are using unmodified config from this repo that does `exec /path/to/session.sh --with-cleanup` (I'll probably make cleanup opt-out instead of opt-in in the next release, as it's proven to be safe).

All I can suggest is to add `set -x` to the head of the script and check the journal output to see if the cleanup code is called.

If you can tell me how to reproduce your exact configuration and environment in a VM, I can take a look this or next weekend.

**Comment by alebastr** [comment]
Well, here is your culprit. `Requires=graphical-session.target` is a very strong dependency and `poweralertd.service` locks `graphical-session.target`, not allowing it to exit. `PartOf=` + `After=` would be a more robust and common option.

Actually, that `Requisite=` in `waybar.service` also looks unhealthy, but it's mostly negated by waybar crashing on compositor exit.

```
alebastr@tileos:~$ systemctl --user list-dependencies --reverse graphical-session.target
graphical-session.target
○ ├─poweralertd.service
× └─waybar.service
alebastr@tileos:~$ systemctl --user cat poweralertd
# /usr/lib/systemd/user/poweralertd.service
[Unit]
Description=UPower-powered power alerter
Documentation=man:poweralertd(1)
PartOf=graphical-session.target
Requires=graphical-session.target

[Service]
Type=simple
ExecStart=/usr/bin/poweralertd

[Install]
WantedBy=graphical-session.target
```

**Comment by alebastr** [comment]
Can you please test #25? It fixes the issue for me, even without modifying the services for poweralertd and waybar.

**Comment by Sunderland93** [comment]
This is fixed the issue for me to! Thank you! Now it works as I expect.

**Comment by alebastr** [comment]
I'll tag a new release with that change in a week or two.
