### ISSUE TITLE
Support not requiring XWayland uner Sway

### ISSUE THREAD

**Issue by grtcdr** [alebastr/sway-systemd#31]
Hi,

Thanks for little gem :)

I tried running this under Sway with the `xwayland` option set to `disable` and the script throws the following error:

    Failed to connect to X11 display:

I traced back the error in the source code to this hunk of code: https://github.com/alebastr/sway-systemd/blob/0e1797be1c36d3e3119f5668d838c17f27f4bc86/src/assign-cgroups.py#L165-L170

I managed to get the script working under my setup, which you may consider a bit of an edge case, by removing all X11-related code. I would still like to see if we can work around this issue by not throwing an exception if the Xlib library is not installed or there is no X display.

**Comment by alebastr** [comment]
The error here is intercepted and should not prevent the script from working. And with sufficiently recent Sway (>= 1.6.1) the X11 connection won't be used.

Anyways, keeping the unused connection wasn't optimal so I changed the X11 fallback code to load on-demand. See #33.

Thanks for reminding me about that.

**Comment by grtcdr** [comment]
Thank you @alebastr for writing a fix :) I'll spin it up on my machine and see how it goes.
