### ISSUE TITLE
wish: Add "How this works" docs

### ISSUE THREAD

**Issue by markstos** [alebastr/sway-systemd#5]
It would be helpful if there some brief docs that covered what files this project provides and how they fit together. For example, cover what behavior happens automatically when this package is installed and what needs to be manually set up.

As an example, I wrote docs like this for the `sway-services` project, although they aren't merged yet.

https://github.com/xdbob/sway-services/pull/19

**Comment by alebastr** [comment]
@markstos I tried to improve documentation in https://github.com/alebastr/sway-systemd/commit/e439b604d7da0b6e564098684552c471aa406d6a. I'm bad at writing docs though, so let me know if you want anything  to be added or explained better :smile:

**Comment by markstos** [comment]
Thanks!

**Comment by markstos** [comment]
The docs seem clear enough, now. Closing.
